#! /usr/bin/bash

if [ $# -lt 1 ]; then
    printf "Należy podać ścieżkę do drzewa katalogów\n"
    exit 1
fi

if [ ! -d $1 ]; then
    echo "Bledny katalog\n"
    exit 2
fi

path=$1

find $path -type f |
awk '\
BEGIN { FS = "/" ; OFS = "Z"}\
$NF ~ /\.exe$|\.exe\..*$/\
'
